[theme]
primaryColor = "#dc3545"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
headless = true
runOnSave = false
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
